# Generated by Django 4.2.5 on 2023-10-16 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_alter_auctionlisting_date_ends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="date_ends",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 23, 13, 25, 9, 959120)
            ),
        ),
    ]
