name: Merge Pull Request
on:
  workflow_run:
   workflows: ["Create Pull request"]
   types: [completed] #requested
jobs:
  merge_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Merge Pull Request
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pullRequest = context.payload.number
          console.log(pullRequest)
